language: node_js
node_js:
  - 6.10.1
before_script:
  - npm install
  - npm install:client
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm test -- --coverage
after_success: "cat ./client/coverage/lcov.info | ./client/node_modules/coveralls/bin/coveralls.js"
